server:
  port: 9005
spring:
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 5000ms
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1ms
  thymeleaf:
    #关闭缓存，及时刷新
    cache: false
    check-template: true
    check-template-location: false
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  #热部署生效
  devtools:
    restart:
      enabled: true
      #排除
      exclude: static/**,public/**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.229.54:3306/huiketong?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
    #allowMultiQueries<-->mysql的批量更新 useSSL<-->MySQL在高版本需要指明是否进行SSL连接
    #url: jdbc:mysql://127.0.0.1:3306/huiketong?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://192.168.0.116:3306/huiketong?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: gxmy2018
    #password: 123456

    other:
      jdbc-url: jdbc:mysql://120.27.229.54:3306/fhadmin?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: gxmy2018


  mail:
    host: smtp.163.com
    username: zuofei_2017@163.com
    password: 3BA512987B116026
    default-encoding: utf-8

pay:
  wxpay:
    #appID: wxb5192e48650a4d77
    appID: wx59b7423faba3495a
    #mchID: 1511035751
    mchID: 1521344991
    #key: BDC8D2693BA512987B11602663771306
    key: 423d8d3db6887e97a6054b34ee29e985
    sandboxKey: c9ab1957323e200c0f6c1439a37b0eba
    #cerPath: /user/server/cert/apiclient_cert.p12
    cerPath: D:/cert/apiclient_cert.p12
    useSandbox: false
  alipay:
    gatewayUrl: https://openapi.alipaydev.com/gateway.do
    appid: 2018121462512890
    appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC1fDXE/od42UTo5aP/nspofTIB+sw1hH8Aqpid3vayzDZdN26DqsSLBAjvvcUopskS2fQPJB1nyzauek9gNvbisnqptH1325dF2wDjgJvxOFTTWUkOW1YhvznlzBi8CHUIeejh2V0LAoDPLOLFRYeav1RIJq3f08iRPJ3XsxCb8JIdyYWK39QIAB7jYtaTKycFE+rPaX+Xx7wYP6LI5eDDCSsTCf3MqPaZTwBFwzc94P0pUZ0HYIgcZGaE03lEcG1Z3pfxNy9TwVpj6E4mNeWk46qi9VLsFZg8nkiYMkpK3A7iFqCfV+4ws4DwzpMoyV05jJ5lDd2Rmqgauj4KveAVAgMBAAECggEAD2vzob7DQkisK2JAMluK9aAV3Mc0DSQqKqNUfq3Qptblk7w/Ht8m/m0kWUL1+wNZOMnejF7URNqm1eK81f81sYPbGoqk0seNLjly9OIb3j6cLq16oMawJgP65oUWYPwS/dpmKLLwzhuzWGeHCZ5j7IlvnwXyZn+3nmfZPdgQhD+jdKnBIYzsC0U6fPZvGYkehugSgHhl3g4XZqU3HAt7k8a7AVOVzHxFANQxgfSj9ukIPaTKsEDM+gpPcMtPEM23HPFn4wYtg6sEv9Q5eD4x7KSaFMc7q++mNBbZPmDcD0tmRILEknzazYnPUNIUYdlJUpFg+fE6ixb1loCyb5aQ7QKBgQDeNqg0q6G4+b1JELxqArZl8uydyiCixpMypzLXQyhilSJ1pYN3QSBwws4RdNiiKl3c7dik8Jdg5IzAIdGu7JXe+Y6oE5R6WYds+D/tK4VBklqr9bj4m6Fhvqerdl6eyQiMfzKEmIwJXCh56dJ0G5GhraagTJxmpkxGbJSS8mTv7wKBgQDRFEMFPUrPy8cZNEqTXQHIkAjOB636cjxUorbAtTLeVYMavYerRVX7Db/BtsDYq8LJIux5Ks4+wu4+laFO9TcAzuOkdQ2+UPHgDPaamkNRy7gUW0JO3Drt613YJUUOAtbiml+rb/QOpMyhruP6drsyA8Cv14aiQMjy91y94hqsOwKBgQCJsBRJjo+Grjg7LcORbFzYjs1OeBAAzEoo+LDn8RT1ALN5cjUjj5cqR4qoBl61HMtMOZQjn3As+XC9HDdwy+eRYdCjFH7L0O2495mku3K2TpkgNAGJCeXVSu1ZsN6wRKCnbak/v8YFhrUN1XQxvWNfatn0OYQvlptsh5sH8mnYwQKBgCPsE0fHLB9fp6mQ7m87P58yABFGCIJLNkpkWnnpp//DOW9SuQiYNRmZVyT1PVT8zc65DWAUFrN50m02UCy8vOKKqVoMMnxMdAJGt+gAMSjQk6QLuezKseVG1yzX2nF502nDlERkS85oSjBNWCYkWC1Tr7uGkD84Wk5Eac7GFkcZAoGALQ9HIjX7PEfhE+UUSG3cDuRJbF1c0mRQ8TvyOuu5MO0UtKWha1K0ytgqVtuClzjH/lfKzSnNIxweagkR/XRYpyfp014a6HDD5C28bmNGsHSxA7wUJxoTRYHDS56hUBAf6sRC0x9h9XG7rY04mXtM9f5Judx5VTFykW5ROwClf/Q=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoGoe3ICZs4Xply8tjUHFtvKoI1T25Wk2W358NS58ImH43TsXSW9xWtubxV7M4spJwL4/jVkrNgyrid58bFfB6eLYOfv5aDZJly7RO4/Lne7dWPlvzGq/aeGwG1H5KkcmORTjrhvxEpKupGXzXLtCjFA40Oo38EFevC+iqJhzIUTzGNlFg1M2STE0rS+ifGjOgE9p4bk863qTUu0kmZf+nNdNRobT8AxICyQz6IL1BFUTyOGY0h9hdYTh7qhfR9tajYdW12zsfvzrEqa0L6rrwsg072e+epEpdojItr9utqXo4HlghUb/6I/BJqQb6NyrX/vif/0bhnVRX4aTi2TNVwIDAQAB
    returnUrl: ""
    notifyUrl: http://jkt365.com/alipay/notify

jiguang:
  appkey: 1cb4077c3dc3741a279a9a25
  masterSecret: ed6ef3b9bc7835095e31f97c

