/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huiketong_cofpasgers_jni_native_HelloJni */

#ifndef _Included_com_huiketong_cofpasgers_jni_native_HelloJni
#define _Included_com_huiketong_cofpasgers_jni_native_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huiketong_cofpasgers_jni_native_HelloJni
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_huiketong_cofpasgers_jni_1native_HelloJni_displayHelloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
